version: "2.2"

services:
  petclinic:
    image: thomasbrn/java-with-docker-spring-petclinic
    ports:
      - "8080:8080"
    networks:
      tbarreno:
        aliases:
          - web
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      tbarreno:
        aliases:
          - db
networks:
  tbarreno:
    driver: bridge
    ipam:
      driver: default

